### PR TITLE
UI changes

### PR DESCRIPTION
**Pull request by Eggn886**
Awsome new ui changes 😎

### CODE REVIEW

**Comment by Eggn886** [comment]
kinda new to github like a bit i forked the repo created a new branch but when i went to check the changes i have some code from the repo missing?

**Comment by Zeldruck** [comment]
It's my fault, the dev branch is behind compared to main, and it should never have happened

**Comment by Zeldruck** [comment]
Can you merge dev/main in your branch and make a new PR, ty.

**Comment by Eggn886** [comment]
sure thing

**Pull request closed without merging**
